In [10]:
import numpy as np

class NeuralNetwork:
    def __init__(self):
        np.random.seed(42)  # 固定隨機種子
        self.wij = np.random.randn(3, 4)  # input to hidden weights
        self.wjk = np.random.randn(4, 1)  # hidden to output weights
        self.lr = 1  # 學習率

    def sigmoid(self, x, w):
        z = np.dot(x, w)
        return 1 / (1 + np.exp(-z))
    
    def sigmoid_derivative(self, x, w):
        return self.sigmoid(x, w) * (1 - self.sigmoid(x, w))

    def gradient_descent(self, x, y, iterations):
        for i in range(iterations):
            Xi = x
            Xj = self.sigmoid(Xi, self.wij)
            yhat = self.sigmoid(Xj, self.wjk)

            # hidden to output weights gradient
            g_wjk = np.dot(Xj.T, (y - yhat) * self.sigmoid_derivative(Xj, self.wjk))
            g_wij = np.dot(Xi.T, np.dot((y - yhat) * self.sigmoid_derivative(Xj, self.wjk), self.wjk.T) * self.sigmoid_derivative(Xi, self.wij))

            # update weights
            self.wjk += self.lr * g_wjk
            self.wij += self.lr * g_wij

            acc = (1 - np.mean(np.abs(yhat - y))) * 100
            print(f"epochs:{i+1} ======= acc:{acc:f}")

        print('The final prediction from neural network are:')
        print(yhat)

if __name__ == '__main__':
    neural_network = NeuralNetwork()
    print('Random starting input to hidden weights:')
    print(neural_network.wij)
    print('Random starting hidden to output weights:')
    print(neural_network.wjk)

    X = np.array([
        [0, 0, 1],
        [1, 1, 1],
        [1, 0, 1],
        [0, 1, 1]
    ])
    y = np.array([[0], [1], [1], [0]])

    neural_network.gradient_descent(X, y, 10000)

Random starting input to hidden weights:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]
Random starting hidden to output weights:
[[ 0.24196227]
 [-1.91328024]
 [-1.72491783]
 [-0.56228753]]
epochs:1 ======= acc:48.794256
epochs:2 ======= acc:48.928873
epochs:3 ======= acc:49.208378
epochs:4 ======= acc:49.740163
epochs:5 ======= acc:50.673371
epochs:6 ======= acc:52.121882
epochs:7 ======= acc:53.969138
epochs:8 ======= acc:55.806522
epochs:9 ======= acc:57.311359
epochs:10 ======= acc:58.493542
epochs:11 ======= acc:59.490359
epochs:12 ======= acc:60.404884
epochs:13 ======= acc:61.292172
epochs:14 ======= acc:62.178482
epochs:15 ======= acc:63.075035
epochs:16 ======= acc:63.985176
epochs:17 ======= acc:64.907992
epochs:18 ======= acc:65.840217
epochs:19 ======= acc:66.777335
epochs:20 ======= acc:67.714259
epochs:21 ======= acc:68.645792
epochs:22 ======= acc:69.566938
epochs: